# -*- coding: utf-8 -*-
"""hw_s9_40.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I-HpLQud2irIWRQ0Xl9fH5B2yxfVTRN3
"""

import pandas as pd

"""##Задача 40
Работать с файлом california_housing_train.csv, который находится в папке sample_data. Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population).
"""

df=pd.read_csv('/content/sample_data/california_housing_train.csv')
#df.sample(20)

df[df['population']<500]['median_house_value'].mean()

"""## Задача 42
Узнать какая максимальная households в зоне минимального значения population.
"""

df[df['population'] == df['population'].min()]['households'].max()